# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='split',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
