# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0002_auto_20180331_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='package',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bud.Supplier'),
        ),
    ]
