# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0002_account_ancestors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ancestors',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u540d\u79f0'),
        ),
    ]
