# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0003_auto_20180331_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bud.Supplier'),
        ),
    ]
