# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0003_auto_20180320_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ancestors',
            field=models.ManyToManyField(related_name='descendants', through='bud.Path', to='bud.Account'),
        ),
    ]
