# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0004_auto_20180331_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='express',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='bvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='bvat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='pvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='pvat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
