# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0005_auto_20180331_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='express',
            new_name='express_in',
        ),
    ]
