# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0006_auto_20180331_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='express_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
