# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0007_commodity_express_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='commodity',
            name='wrap_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
