# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0008_auto_20180331_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ['supplier__id', 'name']},
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='commodity',
            unique_together=set([('supplier', 'name')]),
        ),
    ]
