# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0009_auto_20180331_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bud.Supplier'),
        ),
    ]
