# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0010_auto_20180331_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
