# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0013_auto_20180401_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='bvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u8fdb\u4ef7.\u8d2d\u4e70'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='bvat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u8fdb\u9879\u7a0e.\u8d2d\u4e70'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='express_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u8fd0\u8d39.\u8fdb\u8d27'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='express_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u8fd0\u8d39.\u51fa\u8d27'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u54c1\u540d'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='package',
            field=models.IntegerField(default=0, verbose_name='\u7bb1\u89c4'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='pvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u8fdb\u4ef7.\u6279\u53d1'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='pvat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u8fdb\u9879\u7a0e.\u6279\u53d1'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bud.Supplier', verbose_name='\u4f9b\u5e94\u5546'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='wrap_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u5305\u88c5\u8d39'),
        ),
    ]
