# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0014_auto_20180401_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='abbrev',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
