# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0015_supplier_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='abbrev',
            field=models.CharField(max_length=10),
        ),
    ]
