# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0016_auto_20180410_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='abbrev',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
