# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0017_auto_20180410_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='opath',
            name='ancestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths2descendant', to='bud.Organization'),
        ),
        migrations.AddField(
            model_name='opath',
            name='descendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths2ancestor', to='bud.Organization'),
        ),
    ]
