# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0018_auto_20180410_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ancestors',
            field=models.ManyToManyField(related_name='descendants', through='bud.Opath', to='bud.Organization'),
        ),
    ]
