# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0019_organization_ancestors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['id']},
        ),
    ]
