# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0020_auto_20180410_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Path',
            new_name='Apath',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='\u4f59\u989d'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterUniqueTogether(
            name='opath',
            unique_together=set([('ancestor', 'descendant')]),
        ),
    ]
