# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0021_auto_20180410_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='commodity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bud.Commodity', verbose_name='\u7269\u54c1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bud.Organization', verbose_name='\u96b6\u5c5e\u4e8e'),
            preserve_default=False,
        ),
    ]
