# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud', '0022_auto_20180410_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.IntegerField(choices=[(0, '\u8d44\u4ea7'), (1, '\u8d1f\u503a'), (2, '\u6536\u5165'), (3, '\u652f\u51fa'), (4, '\u51c0\u8d44\u4ea7')], default=0),
        ),
    ]
