# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Organization', verbose_name='\u4e0a\u7ea7'),
        ),
    ]
