# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_auto_20180411_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u54c1\u540d')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u4ef7\u503c')),
            ],
            options={
                'ordering': ['supplier__id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Supplier', verbose_name='\u4f9b\u5e94\u5546'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('supplier', 'name')]),
        ),
    ]
