# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_auto_20180411_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u540d\u79f0')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='\u4f59\u989d')),
                ('category', models.IntegerField(choices=[(0, '\u8d44\u4ea7'), (1, '\u8d1f\u503a'), (2, '\u6536\u5165'), (3, '\u652f\u51fa'), (4, '\u51c0\u8d44\u4ea7')], default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Item', verbose_name='\u7269\u8d44')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Organization', verbose_name='\u7ec4\u7ec7')),
            ],
        ),
    ]
