# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='vault.Organization', verbose_name='\u7ec4\u7ec7'),
        ),
    ]
