# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_auto_20180414_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=120)),
                ('time', models.DateTimeField()),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vault.Task')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.IntegerField(choices=[(0, '\u8d44\u4ea7'), (1, '\u8d1f\u503a'), (2, '\u6536\u5165'), (3, '\u652f\u51fa'), (4, '\u6240\u6709\u8005\u6743\u76ca')], default=0),
        ),
        migrations.AddField(
            model_name='split',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Account'),
        ),
        migrations.AddField(
            model_name='split',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='vault.Transaction'),
        ),
    ]
