# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_auto_20180414_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-time', '-id']},
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u54c1\u540d'),
        ),
    ]
