# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_auto_20180501_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inproduction',
            field=models.BooleanField(default=True, verbose_name=b'\xe5\x9c\xa8\xe4\xba\xa7'),
        ),
        migrations.AddField(
            model_name='item',
            name='onsale',
            field=models.BooleanField(default=True, verbose_name=b'\xe5\x9c\xa8\xe5\x94\xae'),
        ),
    ]
