# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_auto_20180501_1936'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jdcommoditymap',
            unique_together=set([('jdcommodity', 'since')]),
        ),
    ]
