# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_auto_20180501_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jdorder',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name=b'\xe4\xba\xac\xe4\xb8\x9c\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7')),
                ('status', models.CharField(max_length=30, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vault.Task')),
            ],
        ),
    ]
