# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_auto_20180506_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jdcommodity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe7\xbc\x96\xe7\xa0\x81')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='jdcommoditymap',
            name='jdcommodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='vault.Jdcommodity'),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
    ]
