# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_auto_20180506_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jdcommodity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='jdcommoditymap',
            options={'ordering': ['jdcommodity', '-since']},
        ),
        migrations.AddField(
            model_name='jdorder',
            name='fake',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\x88\xb7\xe5\x8d\x95'),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='status',
            field=models.IntegerField(choices=[(0, b'\xe7\xad\x89\xe5\xbe\x85\xe5\x87\xba\xe5\xba\x93'), (1, b'\xe7\xad\x89\xe5\xbe\x85\xe7\xa1\xae\xe8\xae\xa4\xe6\x94\xb6\xe8\xb4\xa7'), (2, b'\xe5\xae\x8c\xe6\x88\x90'), (3, b'(\xe5\x88\xa0\xe9\x99\xa4)\xe9\x94\x81\xe5\xae\x9a'), (4, b'(\xe5\x88\xa0\xe9\x99\xa4)\xe7\xad\x89\xe5\xbe\x85\xe5\x87\xba\xe5\xba\x93'), (5, b'(\xe5\x88\xa0\xe9\x99\xa4)\xe7\xad\x89\xe5\xbe\x85\xe7\xa1\xae\xe8\xae\xa4\xe6\x94\xb6\xe8\xb4\xa7')], verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('organization', 'item', 'category', 'name')]),
        ),
    ]
