# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0017_auto_20180520_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmcommodity',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe7\xbc\x96\xe7\xa0\x81')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tmcommoditymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(verbose_name=b'\xe7\x94\x9f\xe6\x95\x88\xe6\x97\xb6\xe9\x97\xb4')),
                ('items', models.ManyToManyField(to='vault.Item', verbose_name=b'\xe7\x89\xa9\xe5\x93\x81')),
                ('tmcommodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Tmcommodity')),
            ],
            options={
                'ordering': ['tmcommodity', '-since'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tmcommoditymap',
            unique_together=set([('tmcommodity', 'since')]),
        ),
    ]
