# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0020_tmorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmorder',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
