# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0022_auto_20180522_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cleared',
            new_name='clear',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='settled',
            new_name='settle',
        ),
    ]
