# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0024_auto_20180525_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Repository', verbose_name=b'\xe4\xbb\x93\xe5\xba\x93'),
        ),
    ]
