# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0024_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='repository',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='vault.Repository', verbose_name=b'\xe4\xbb\x93\xe5\xba\x93'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
