# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0024_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vault.Repository', verbose_name=b'\xe4\xbb\x93\xe5\xba\x93'),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.IntegerField(choices=[(0, b'\xe8\xb5\x84\xe4\xba\xa7'), (1, b'\xe8\xb4\x9f\xe5\x80\xba'), (2, b'\xe6\x94\xb6\xe5\x85\xa5'), (3, b'\xe6\x94\xaf\xe5\x87\xba'), (4, b'\xe6\x89\x80\xe6\x9c\x89\xe8\x80\x85\xe6\x9d\x83\xe7\x9b\x8a')], default=0, verbose_name=b'\xe4\xbc\x9a\xe8\xae\xa1\xe7\xb1\xbb\xe7\x9b\xae'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
