# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0026_auto_20180525_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='item',
            name='inproduction',
        ),
        migrations.RemoveField(
            model_name='item',
            name='onsale',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='item',
            name='value',
        ),
    ]
