# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0027_auto_20180525_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.Item')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name=b'\xe4\xbb\xb7\xe5\x80\xbc')),
                ('onsale', models.BooleanField(default=True, verbose_name=b'\xe5\x9c\xa8\xe5\x94\xae')),
                ('inproduction', models.BooleanField(default=True, verbose_name=b'\xe5\x9c\xa8\xe4\xba\xa7')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Supplier', verbose_name=b'\xe4\xbe\x9b\xe5\xba\x94\xe5\x95\x86')),
            ],
            bases=('vault.item',),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
    ]
