# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0028_auto_20180525_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.Item')),
            ],
            bases=('vault.item',),
        ),
    ]
