# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0032_jdorder_repository'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('organization', 'item', 'category', 'repository', 'name')]),
        ),
    ]
