# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0034_auto_20180527_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmorder',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vault.Repository'),
        ),
    ]
