# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0035_tmorder_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmorder',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Repository'),
        ),
    ]
