# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0036_auto_20180527_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdorder',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
