# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0038_tmorder_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jdorder',
            old_name='id',
            new_name='oid',
        ),
        migrations.RemoveField(
            model_name='jdorder',
            name='task',
        ),
        migrations.AddField(
            model_name='jdorder',
            name='task_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='vault.Task'),
            preserve_default=False,
        ),
    ]
