# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0039_auto_20180603_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdorder',
            name='oid',
            field=models.BigIntegerField(unique=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='task_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.Task'),
        ),
    ]
