# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0040_auto_20180603_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tmorder',
            name='task',
        ),
        migrations.AddField(
            model_name='tmorder',
            name='oid',
            field=models.BigIntegerField(default=1, unique=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmorder',
            name='task_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.Task'),
            preserve_default=False,
        ),
    ]
