# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0041_auto_20180603_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdorder',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Repository'),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, b'\xe7\xad\x89\xe5\xbe\x85\xe5\x87\xba\xe5\xba\x93'), (1, b'\xe7\xad\x89\xe5\xbe\x85\xe7\xa1\xae\xe8\xae\xa4\xe6\x94\xb6\xe8\xb4\xa7'), (2, b'\xe5\xae\x8c\xe6\x88\x90'), (3, b'(\xe5\x88\xa0\xe9\x99\xa4)\xe9\x94\x81\xe5\xae\x9a'), (4, b'(\xe5\x88\xa0\xe9\x99\xa4)\xe7\xad\x89\xe5\xbe\x85\xe5\x87\xba\xe5\xba\x93'), (5, b'(\xe5\x88\xa0\xe9\x99\xa4)\xe7\xad\x89\xe5\xbe\x85\xe7\xa1\xae\xe8\xae\xa4\xe6\x94\xb6\xe8\xb4\xa7'), (6, b'\xe9\x94\x81\xe5\xae\x9a')], null=True, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
