# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0042_auto_20180608_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='clear',
        ),
        migrations.RemoveField(
            model_name='task',
            name='settle',
        ),
    ]
