# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0043_auto_20180608_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmorder',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Repository'),
        ),
        migrations.AlterField(
            model_name='tmorder',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, b'\xe7\xad\x89\xe5\xbe\x85\xe4\xb9\xb0\xe5\xae\xb6\xe4\xbb\x98\xe6\xac\xbe'), (1, b'\xe4\xb9\xb0\xe5\xae\xb6\xe5\xb7\xb2\xe4\xbb\x98\xe6\xac\xbe\xef\xbc\x8c\xe7\xad\x89\xe5\xbe\x85\xe5\x8d\x96\xe5\xae\xb6\xe5\x8f\x91\xe8\xb4\xa7'), (2, b'\xe5\x8d\x96\xe5\xae\xb6\xe5\xb7\xb2\xe5\x8f\x91\xe8\xb4\xa7\xef\xbc\x8c\xe7\xad\x89\xe5\xbe\x85\xe4\xb9\xb0\xe5\xae\xb6\xe7\xa1\xae\xe8\xae\xa4'), (3, b'\xe4\xba\xa4\xe6\x98\x93\xe6\x88\x90\xe5\x8a\x9f'), (4, b'\xe4\xba\xa4\xe6\x98\x93\xe5\x85\xb3\xe9\x97\xad')], null=True, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
