# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0044_auto_20180609_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='period',
            field=models.IntegerField(default=15),
        ),
    ]
