# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0045_auto_20180619_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterfeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name=b'\xe5\xb9\xb3\xe5\x8f\xb0')),
                ('delivery', models.BooleanField(verbose_name=b'\xe7\x9c\x9f\xe5\xae\x9e\xe5\x8f\x91\xe8\xb4\xa7')),
                ('recall', models.BooleanField(verbose_name=b'\xe5\xae\x9e\xe7\x89\xa9\xe5\x9b\x9e\xe6\x94\xb6')),
            ],
        ),
    ]
