# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0048_auto_20180619_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmorder',
            name='counterfeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Counterfeit', verbose_name=b'\xe5\x88\xb7\xe5\x8d\x95\xe5\xb9\xb3\xe5\x8f\xb0'),
        ),
        migrations.AddField(
            model_name='tmorder',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name=b'\xe7\x9c\x9f\xe5\xae\x9e\xe5\x8f\x91\xe8\xb4\xa7'),
        ),
        migrations.AddField(
            model_name='tmorder',
            name='recall',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\xae\x9e\xe7\x89\xa9\xe5\x9b\x9e\xe6\x94\xb6'),
        ),
        migrations.AddField(
            model_name='tmorder',
            name='recall_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_tmorder_recall_order_set', related_query_name='vault_tmorder_recall', to='vault.Repository'),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='recall_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_jdorder_recall_order_set', related_query_name='vault_jdorder_recall', to='vault.Repository'),
        ),
    ]
