# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0049_auto_20180619_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdorder',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_jdorder_order_set', related_query_name='vault_jdorder', to='vault.Repository'),
        ),
        migrations.AlterField(
            model_name='tmorder',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_tmorder_order_set', related_query_name='vault_tmorder', to='vault.Repository'),
        ),
    ]
