# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0050_auto_20180619_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdorder',
            name='recall_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_jdorder_recall_order_set', related_query_name='vault_jdorder_recall', to='vault.Repository', verbose_name=b'\xe5\x88\xb7\xe5\x8d\x95\xe5\x9b\x9e\xe6\x94\xb6\xe4\xbb\x93\xe5\xba\x93'),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_jdorder_order_set', related_query_name='vault_jdorder', to='vault.Repository', verbose_name=b'\xe5\x8f\x91\xe8\xb4\xa7\xe4\xbb\x93\xe5\xba\x93'),
        ),
        migrations.AlterField(
            model_name='tmorder',
            name='recall_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_tmorder_recall_order_set', related_query_name='vault_tmorder_recall', to='vault.Repository', verbose_name=b'\xe5\x88\xb7\xe5\x8d\x95\xe5\x9b\x9e\xe6\x94\xb6\xe4\xbb\x93\xe5\xba\x93'),
        ),
        migrations.AlterField(
            model_name='tmorder',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_tmorder_order_set', related_query_name='vault_tmorder', to='vault.Repository', verbose_name=b'\xe5\x8f\x91\xe8\xb4\xa7\xe4\xbb\x93\xe5\xba\x93'),
        ),
    ]
