# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0051_auto_20180619_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='calibration',
            field=models.DateTimeField(default=datetime.datetime(2009, 12, 31, 16, 0, tzinfo=utc)),
        ),
    ]
