# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0054_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
