# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0056_auto_20180627_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
