# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0058_auto_20180628_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdorder',
            name='counterfeit_auto_clear',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x88\xb7\xe5\x8d\x95\xe8\x87\xaa\xe5\x8a\xa8\xe7\xbb\x93\xe7\xae\x97'),
        ),
        migrations.AddField(
            model_name='tmorder',
            name='counterfeit_auto_clear',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x88\xb7\xe5\x8d\x95\xe8\x87\xaa\xe5\x8a\xa8\xe7\xbb\x93\xe7\xae\x97'),
        ),
    ]
