# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0059_auto_20180630_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='obsolete',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\xba\x9f\xe5\xbc\x83'),
        ),
    ]
