# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0060_commodity_obsolete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdorder',
            name='fake',
        ),
        migrations.RemoveField(
            model_name='tmorder',
            name='fake',
        ),
    ]
