# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0061_auto_20180705_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='onsale',
        ),
    ]
