# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0062_remove_commodity_onsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.BigIntegerField(verbose_name=b'\xe5\xbf\xab\xe9\x80\x92\xe5\x8d\x95\xe5\x8f\xb7')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name=b'\xe8\xbf\x90\xe8\xb4\xb9')),
                ('clear', models.BooleanField(default=False, verbose_name=b'\xe5\xb7\xb2\xe7\xbb\x93\xe7\xae\x97')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='express',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.ExpressSupplier', verbose_name=b'\xe5\xbf\xab\xe9\x80\x92\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x95\x86'),
        ),
        migrations.AddField(
            model_name='express',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='express',
            unique_together=set([('supplier', 'eid')]),
        ),
    ]
