# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0063_auto_20180709_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmclear',
            fields=[
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe5\xae\x9d\xe6\xb5\x81\xe6\xb0\xb4\xe5\x8f\xb7')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vault.Transaction')),
            ],
        ),
    ]
