# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0064_tmclear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jdorderclear',
            fields=[
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name=b'\xe5\x8d\x95\xe6\x8d\xae\xe7\xbc\x96\xe5\x8f\xb7')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vault.Transaction')),
            ],
        ),
    ]
