# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0065_jdorderclear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jdwalletclear',
            fields=[
                ('pid', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name=b'\xe5\x95\x86\xe6\x88\xb7\xe8\xae\xa2\xe5\x8d\x95\xe5\x8f\xb7')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vault.Transaction')),
            ],
        ),
    ]
