# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0066_jdwalletclear'),
    ]

    operations = [
        migrations.CreateModel(
            name='JdadvertiseClear',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'\xe5\xba\x8f\xe5\x8f\xb7')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vault.Transaction')),
            ],
        ),
    ]
