# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0068_auto_20180822_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='package',
            field=models.IntegerField(default=1, verbose_name=b'\xe7\xae\xb1\xe8\xa7\x84'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='proxy',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x88\x86\xe9\x94\x80'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='wrap',
            field=models.CharField(blank=True, max_length=1024, verbose_name=b'\xe5\x8c\x85\xe8\xa3\x85'),
        ),
    ]
