# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0069_auto_20180904_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='calibration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
