# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0071_calibrationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xe7\xbb\x84\xe5\x90\x88\xe5\x90\x8d\xe7\xa7\xb0')),
                ('commodities', models.ManyToManyField(to='vault.Commodity', verbose_name=b'\xe5\x95\x86\xe5\x93\x81')),
            ],
        ),
        migrations.AlterModelOptions(
            name='calibrationhistory',
            options={'ordering': ['-utc']},
        ),
    ]
