# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0072_auto_20181225_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='counterfeit',
            field=models.BooleanField(default=True, verbose_name=b'\xe5\x88\xb7\xe6\x89\x8b\xe6\xa0\x87\xe8\xae\xb0'),
        ),
        migrations.AddField(
            model_name='customer',
            name='recruit',
            field=models.IntegerField(default=0, verbose_name=b'\xe6\x8b\x9b\xe5\x8b\x9f\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='join',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\x88\x9d\xe6\xac\xa1\xe4\xb8\x8b\xe5\x8d\x95\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
