# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0072_auto_20181220_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vault.Address', verbose_name=b'\xe4\xb8\x8a\xe7\xba\xa7')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('phone', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Customer'),
        ),
        migrations.AddField(
            model_name='jdorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Address', verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='jdorder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Contact', verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
        migrations.AddField(
            model_name='tmorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Address', verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='tmorder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Contact', verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
    ]
