# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0072_auto_20181220_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.IntegerField(default=0, verbose_name=b'\xe5\xb1\x82\xe7\xba\xa7')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vault.Address', verbose_name=b'\xe4\xb8\x8a\xe7\xba\xa7')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('phone', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('join', models.IntegerField(default=0, verbose_name=b'\xe5\x88\x9d\xe6\xac\xa1\xe4\xb8\x8b\xe5\x8d\x95\xe6\x97\xb6\xe9\x97\xb4')),
                ('counterfeit', models.BooleanField(default=True, verbose_name=b'\xe5\x88\xb7\xe6\x89\x8b\xe6\xa0\x87\xe8\xae\xb0')),
                ('recruit', models.IntegerField(default=0, verbose_name=b'\xe6\x8b\x9b\xe5\x8b\x9f\xe6\x97\xb6\xe9\x97\xb4')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.Customer'),
        ),
        migrations.AddField(
            model_name='jdorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Address', verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='jdorder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Contact', verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
        migrations.AddField(
            model_name='tmorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Address', verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='tmorder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.Contact', verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('name', 'parent')]),
        ),
    ]
