# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0073_auto_20181224_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='level',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\xb1\x82\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
