# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0073_auto_20181226_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='abbrev',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name=b'\xe7\xae\x80\xe7\xa7\xb0'),
        ),
    ]
