# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0074_auto_20181224_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
