# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0075_auto_20181224_1814'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('name', 'parent')]),
        ),
    ]
